### ISSUE TITLE
ValueError

### ISSUE THREAD

**Issue by RayOct18** [RayOct18/pyobfuscator#2]
```bash
Traceback (most recent call last):
  File "/home/rayxie/anaconda3/envs/test/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/rayxie/anaconda3/envs/test/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/rayxie/anaconda3/envs/test/lib/python3.8/site-packages/pobfuscatory/__main__.py", line 62, in <module>
    obfuscator.obfuscate()
  File "/home/rayxie/anaconda3/envs/test/lib/python3.8/site-packages/pobfuscatory/obfuscator.py", line 170, in obfuscate
    self._process(
  File "/home/rayxie/anaconda3/envs/test/lib/python3.8/site-packages/pobfuscatory/obfuscator.py", line 193, in _process
    func(file_dir)
  File "/home/rayxie/anaconda3/envs/test/lib/python3.8/site-packages/pobfuscatory/obfuscator.py", line 171, in <lambda>
    lambda x: convert(
  File "/home/rayxie/anaconda3/envs/test/lib/python3.8/site-packages/pobfuscatory/obfuscator.py", line 369, in convert
    target_dir = os.path.join(target, *sp[sp.index(root) + 1 :])
ValueError: '' is not in list
```

**Comment by RayOct18** [comment]
fixed [1daef1d](https://github.com/RayOct18/pobfuscatory/commit/1daef1de0210b97e8e1bb8b10eaac6dcd839b6ba)
