### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by RayOct18** [RayOct18/pyobfuscator#5]
some library can not be installed on pypi. it needs to be ignored.
```bash
Traceback (most recent call last):
  File "/home/rayxie/anaconda3/envs/test/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/rayxie/anaconda3/envs/test/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/rayxie/anaconda3/envs/test/lib/python3.8/site-packages/pobfuscatory/__main__.py", line 62, in <module>
    obfuscator.obfuscate()
  File "/home/rayxie/anaconda3/envs/test/lib/python3.8/site-packages/pobfuscatory/obfuscator.py", line 164, in obfuscate
    self._process(scan.run)
  File "/home/rayxie/anaconda3/envs/test/lib/python3.8/site-packages/pobfuscatory/obfuscator.py", line 193, in _process
    func(file_dir)
  File "/home/rayxie/anaconda3/envs/test/lib/python3.8/site-packages/pobfuscatory/obfuscator.py", line 246, in run
    subclass(self.root, self.keys)._execute(line, f)
  File "/home/rayxie/anaconda3/envs/test/lib/python3.8/site-packages/pobfuscatory/obfuscator.py", line 344, in _execute
    exec(line)
  File "<string>", line 1, in <module>
  File "/home/rayxie/anaconda3/envs/test/lib/python3.8/site-packages/airtest/core/win/__init__.py", line 4, in <module>
    from .win import Windows
  File "/home/rayxie/anaconda3/envs/test/lib/python3.8/site-packages/airtest/core/win/win.py", line 8, in <module>
    import pywintypes  # noqa
ModuleNotFoundError: No module named 'pywintypes'
```

**Comment by RayOct18** [comment]
fix [1579eb4](https://github.com/RayOct18/pobfuscatory/commit/1579eb4389e01d6f8c33cbf4f3f70f6542d5a3c6)
